# Generated by Django 3.2.5 on 2022-09-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandmas_kitchen', '0003_familymemberrelation_recipe_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ManyToManyField(to='grandmas_kitchen.Ingredient')),
                ('recipe', models.ManyToManyField(to='grandmas_kitchen.Recipe')),
            ],
        ),
    ]
